-- ── Seed Events ───────────────────────────────────────────────────────────
INSERT INTO public.events (name, location, time, tag, emoji) VALUES
  ('Chai & Chat',      'Mathews Pavilion, UNSW',  '2026-06-20 18:00:00+10', 'Social',   '☕'),
  ('Eid Gala 2026',    'Roundhouse, UNSW',         '2026-06-28 19:00:00+10', 'Flagship', '🌙'),
  ('Cricket Carnival', 'UNSW Oval, Kensington',    '2026-07-13 10:00:00+10', 'Sports',   '🏏')
ON CONFLICT DO NOTHING;

-- ── Seed Members ──────────────────────────────────────────────────────────
INSERT INTO public.members (name, role, committee) VALUES
  ('Usman Farooq',   'President', 'Presidents'),
  ('Hiba Siddiqui',  'VP',        'Presidents'),
  ('Raza Mahmood',   'VP',        'Presidents'),
  ('Ahmed Khan',     'Exec',      'Sports'),
  ('Zara Ali',       'Exec',      'Sports'),
  ('Faisal Ahmed',   'Exec',      'Sports'),
  ('Hassan Malik',   'Subcom',    'Sports'),
  ('Fatima Raza',    'Subcom',    'Sports'),
  ('Bilal Chaudhry', 'Subcom',    'Sports'),
  ('Mariam Qureshi', 'Subcom',    'Sports'),
  ('Asad Baig',      'Subcom',    'Sports'),
  ('Noor Hussain',   'Subcom',    'Sports'),
  ('Sadia Mirza',    'Subcom',    'Sports'),
  ('Junaid Sheikh',  'Subcom',    'Sports'),
  ('Amna Tariq',     'Subcom',    'Sports'),
  ('Umar Iqbal',     'Subcom',    'Sports'),
  ('Rabia Siddiqui', 'Subcom',    'Sports'),
  ('Sara Sheikh',    'Exec',      'Marketing'),
  ('Hamza Farooq',   'Exec',      'Marketing'),
  ('Hasan Raza',     'Exec',      'Marketing'),
  ('Omar Qureshi',   'Subcom',    'Marketing'),
  ('Aisha Baig',     'Subcom',    'Marketing'),
  ('Nadia Ali',      'Subcom',    'Marketing'),
  ('Talha Khan',     'Subcom',    'Marketing'),
  ('Sana Malik',     'Subcom',    'Marketing'),
  ('Zainab Ahmed',   'Subcom',    'Marketing'),
  ('Irfan Hussain',  'Subcom',    'Marketing'),
  ('Nadia Hussain',  'Exec',      'Events'),
  ('Kamran Mirza',   'Exec',      'Events'),
  ('Rizwan Malik',   'Exec',      'Events'),
  ('Layla Rahman',   'Exec',      'Events'),
  ('Imran Siddiqui', 'Subcom',    'Events'),
  ('Ayesha Baig',    'Subcom',    'Events'),
  ('Shahzaib Ali',   'Subcom',    'Events'),
  ('Mehwish Khan',   'Subcom',    'Events'),
  ('Daniyal Raza',   'Subcom',    'Events'),
  ('Farah Qureshi',  'Subcom',    'Events'),
  ('Saira Ahmed',    'Subcom',    'Events'),
  ('Moiz Sheikh',    'Subcom',    'Events'),
  ('Hira Tariq',     'Subcom',    'Events'),
  ('Adnan Hussain',  'Subcom',    'Events'),
  ('Maryam Iqbal',   'Subcom',    'Events'),
  ('Asim Farooq',    'Subcom',    'Events'),
  ('Rubab Siddiqui', 'Subcom',    'Events'),
  ('Waqas Ali',      'Subcom',    'Events'),
  ('Zunera Khan',    'Subcom',    'Events'),
  ('Tariq Iqbal',    'Subcom',    'Events'),
  ('Dua Malik',      'Exec',      'HR'),
  ('Fariha Raza',    'Exec',      'HR'),
  ('Saad Akhtar',    'Subcom',    'HR'),
  ('Maham Iqbal',    'Subcom',    'HR'),
  ('Jawad Sheikh',   'Subcom',    'HR')
ON CONFLICT DO NOTHING;
