import { LegalPageLayout, LegalSection, LegalList, LegalParagraph } from './LegalPageLayout'

export default function TermsOfService() {
  return (
    <LegalPageLayout title="Terms of Service — UNSW PakSoc Manager">
      <LegalSection title="1. Acceptance of Terms">
        <LegalParagraph>
          By logging into the UNSW PakSoc Manager, you agree to comply with these terms.
        </LegalParagraph>
      </LegalSection>

      <LegalSection title="2. Description of Service">
        <LegalParagraph>
          This portal provides event management, an Instagram social feed, location mapping for venues,
          and internal communication tools for UNSW PakSoc.
        </LegalParagraph>
      </LegalSection>

      <LegalSection title="3. User Conduct">
        <LegalList items={[
          'Internal Chat: Users must remain professional and respectful in the live chat.',
          'Scraping: The Instagram scraper and mapping features are for society informational use only.',
          'RBAC: Users must not attempt to bypass their assigned role (Admin, Sub-committee, or Member) to access unauthorized data.',
        ]} />
      </LegalSection>

      <LegalSection title="4. QR Codes & Registration">
        <LegalParagraph>
          QR codes generated by this system are for official society registration purposes only.
        </LegalParagraph>
      </LegalSection>

      <LegalSection title="5. Limitation of Liability">
        <LegalParagraph>
          This is a student-led platform. UNSW PakSoc and its developers are not liable for any
          temporary service interruptions or data inaccuracies in the mapping/scraping tools.
        </LegalParagraph>
      </LegalSection>

      <LegalSection title="6. Governing Law">
        <LegalParagraph>
          These terms are governed by the laws of New South Wales, Australia.
        </LegalParagraph>
      </LegalSection>
    </LegalPageLayout>
  )
}
